export const categories = [
  {
    id: 1,
    name: "Protein",
    slug: "protein",
    description: "High-quality protein supplements for optimal muscle growth",
    image: "/17453904874404f51hnqt.png",
  },
  {
    id: 2,
    name: "Pre-Workout",
    slug: "pre-workout",
    description: "Energy-boosting formulas for maximum workout performance",
    image: "/17453904874404f51hnqt.png",
  },
  {
    id: 3,
    name: "Creatine",
    slug: "creatine",
    description: "Increase strength and power output with premium creatine",
    image: "/17453904874404f51hnqt.png",
  },
  {
    id: 4,
    name: "Mass Gainers",
    slug: "mass-gainers",
    description:
      "Calorie-dense formulas for those looking to build serious mass",
    image: "/17453904874404f51hnqt.png",
  },
  {
    id: 5,
    name: "BCAAs",
    slug: "bcaas",
    description:
      "Branched-chain amino acids for improved recovery and performance",
    image: "/17453904874404f51hnqt.png",
  },
  {
    id: 6,
    name: "Vitamins & Minerals",
    slug: "vitamins-minerals",
    description: "Essential micronutrients for overall health and performance",
    image: "/17453904874404f51hnqt.png",
  },
];

export const products = [
  {
    id: 1,
    name: "Quantum Whey Isolate",
    slug: "quantum-whey-isolate",
    description:
      "Ultra-filtered whey protein isolate with 27g protein per serving and zero sugar. Engineered for maximum absorption and muscle synthesis.",
    price: 4999,
    discount: 0,
    categoryId: 1,
    rating: 4.9,
    stock: 50,
    tags: ["Protein", "Muscle Growth", "Recovery"],
    isVegan: false,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "27g protein per serving",
      "Zero sugar",
      "Enhanced with digestive enzymes",
      "25 servings per container",
    ],
    flavors: ["Chocolate", "Vanilla", "Strawberry", "Cookies & Cream"],
    sizes: [
      { name: "1.5 lbs", price: 4999 },
      { name: "3 lbs", price: 8499 },
      { name: "5 lbs", price: 11999 },
    ],
  },
  {
    id: 2,
    name: "Nova Surge Pre-Workout",
    slug: "nova-surge-pre-workout",
    description:
      "Revolutionary pre-workout formula with cognitive enhancers and sustained energy release. Experience laser focus and explosive power without the crash.",
    price: 3999,
    discount: 10,
    categoryId: 2,
    rating: 4.7,
    stock: 35,
    tags: ["Pre-Workout", "Energy", "Focus"],
    isVegan: true,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "Cognitive enhancers for focus",
      "Sustained energy release",
      "No artificial colors",
      "30 servings per container",
    ],
    flavors: ["Blue Raspberry", "Watermelon", "Fruit Punch", "Orange"],
    sizes: [
      { name: "30 servings", price: 3999 },
      { name: "60 servings", price: 7499 },
    ],
  },
  {
    id: 3,
    name: "Matrix Micronized Creatine",
    slug: "matrix-micronized-creatine",
    description:
      "Ultra-pure micronized creatine monohydrate for enhanced absorption and results. Scientifically proven to increase strength and power output.",
    price: 2499,
    discount: 0,
    categoryId: 3,
    rating: 4.8,
    stock: 65,
    tags: ["Creatine", "Strength", "Power"],
    isVegan: true,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "5g pure creatine per serving",
      "Micronized for better absorption",
      "Unflavored for easy mixing",
      "100 servings per container",
    ],
    flavors: ["Unflavored"],
    sizes: [
      { name: "300g", price: 2499 },
      { name: "500g", price: 3799 },
      { name: "1kg", price: 6799 },
    ],
  },
  {
    id: 4,
    name: "Titan Mass Gainer",
    slug: "titan-mass-gainer",
    description:
      "Premium mass gainer with complex carbs and quality protein in a 3:1 ratio. Engineered for serious mass and size gains.",
    price: 5999,
    discount: 5,
    categoryId: 4,
    rating: 4.5,
    stock: 40,
    tags: ["Mass Gainer", "Weight Gain", "Muscle"],
    isVegan: false,
    isGlutenFree: false,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "1250 calories per serving",
      "50g protein per serving",
      "250g carbs per serving",
      "Added digestive enzymes",
    ],
    flavors: ["Chocolate", "Vanilla", "Strawberry"],
    sizes: [
      { name: "6 lbs", price: 5999 },
      { name: "12 lbs", price: 9999 },
    ],
  },
  {
    id: 5,
    name: "Vortex BCAA Complex",
    slug: "vortex-bcaa-complex",
    description:
      "Advanced BCAA formula with optimal 2:1:1 ratio of leucine, isoleucine, and valine. Enhanced with electrolytes for hydration and recovery.",
    price: 3499,
    discount: 0,
    categoryId: 5,
    rating: 4.6,
    stock: 55,
    tags: ["BCAA", "Recovery", "Endurance"],
    isVegan: true,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "7g BCAAs per serving",
      "2:1:1 ratio for optimal results",
      "Added electrolytes",
      "30 servings per container",
    ],
    flavors: ["Blue Raspberry", "Watermelon", "Peach Mango", "Unflavored"],
    sizes: [
      { name: "30 servings", price: 3499 },
      { name: "60 servings", price: 5999 },
    ],
  },
  {
    id: 6,
    name: "Zenith Multivitamin",
    slug: "zenith-multivitamin",
    description:
      "Complete multivitamin formula designed specifically for athletes and active individuals. Supports immune function, energy, and recovery.",
    price: 2999,
    discount: 15,
    categoryId: 6,
    rating: 4.7,
    stock: 70,
    tags: ["Vitamins", "Health", "Immune Support"],
    isVegan: true,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "100% daily values of essential vitamins",
      "Enhanced with antioxidants",
      "Athletic performance blend",
      "60 capsules per bottle",
    ],
    flavors: [],
    sizes: [
      { name: "60 capsules", price: 2999 },
      { name: "120 capsules", price: 4999 },
    ],
  },
  {
    id: 7,
    name: "Apex Plant Protein",
    slug: "apex-plant-protein",
    description:
      "Premium plant-based protein blend with pea, rice, and hemp proteins. Complete amino acid profile with 24g protein per serving.",
    price: 4499,
    discount: 0,
    categoryId: 1,
    rating: 4.5,
    stock: 45,
    tags: ["Protein", "Plant-Based", "Vegan"],
    isVegan: true,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "24g plant protein per serving",
      "Complete amino acid profile",
      "Added digestive enzymes",
      "20 servings per container",
    ],
    flavors: ["Chocolate", "Vanilla", "Berry"],
    sizes: [
      { name: "1.5 lbs", price: 4499 },
      { name: "3 lbs", price: 7999 },
    ],
  },
  {
    id: 8,
    name: "Pulse Stim-Free Pre-Workout",
    slug: "pulse-stim-free-pre-workout",
    description:
      "Caffeine-free pre-workout formula for evening training or stimulant-sensitive individuals. Enhances pump, endurance, and focus without stimulants.",
    price: 3699,
    discount: 0,
    categoryId: 2,
    rating: 4.4,
    stock: 30,
    tags: ["Pre-Workout", "Stimulant-Free", "Pump"],
    isVegan: true,
    isGlutenFree: true,
    image: "/17453904874404f51hnqt.png",
    images: [
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
      "/17453904874404f51hnqt.png",
    ],
    features: [
      "Caffeine-free formula",
      "Enhanced with L-Citrulline for pump",
      "Added nootropics for focus",
      "30 servings per container",
    ],
    flavors: ["Fruit Punch", "Berry Blast", "Lemon Lime"],
    sizes: [
      { name: "30 servings", price: 3699 },
      { name: "60 servings", price: 6799 },
    ],
  },
];

export const getProductsByCategory = (categoryId) => {
  return products.filter((product) => product.categoryId === categoryId);
};

export const getProductBySlug = (slug) => {
  return products.find((product) => product.slug === slug);
};
